## Generated by tools/sdk_gen.py from docs/openapi-v1.json: don't edit it; change the server, then regenerate.
##
## The /v1 contract in GDScript: a class per schema, with typed fields, and the route table the client calls
## through. Each class reads itself from a reply (`read`, whole numbers back to int, as GDScript's JSON makes
## every number a float) and writes itself as a request body (`to_dict`, leaving out what's null).
class_name ThespisApi
extends RefCounted

const VERSION := "v1"

## Each route: [method, path, request class name or "", reply class name or ""]. Paths keep their {params}.
const ROUTES := {
	"list_games": ["GET", "/v1/games", "", "GameOut"],
	"delete_game": ["DELETE", "/v1/games/{gid}", "", ""],
	"put_game": ["PUT", "/v1/games/{gid}", "GameIn", "GameOut"],
	"health": ["GET", "/v1/health", "", "HealthOut"],
	"get_project": ["GET", "/v1/project", "", "ProjectOut"],
	"delete_model": ["DELETE", "/v1/project/model", "", ""],
	"put_model": ["PUT", "/v1/project/model", "ModelIn", ""],
	"open_session": ["POST", "/v1/sessions", "SessionIn", "SessionOut"],
	"close_session": ["DELETE", "/v1/sessions/{sid}", "", ""],
	"decide": ["POST", "/v1/sessions/{sid}/decide", "DecideIn", "LineOut"],
	"line": ["GET", "/v1/sessions/{sid}/lines/{lid}", "", "LineOut"],
	"narrate": ["POST", "/v1/sessions/{sid}/narrate", "NarrateIn", "LineOut"],
	"add": ["POST", "/v1/sessions/{sid}/npcs", "NpcIn", ""],
	"retire": ["DELETE", "/v1/sessions/{sid}/npcs/{npc}", "", ""],
	"inspect": ["GET", "/v1/sessions/{sid}/npcs/{npc}", "", "NpcOut"],
	"observe": ["POST", "/v1/sessions/{sid}/observe", "ObserveIn", "EventOut"],
	"join": ["POST", "/v1/sessions/{sid}/players", "JoinIn", ""],
	"react": ["POST", "/v1/sessions/{sid}/react", "ReactIn", "LineOut"],
	"snapshot": ["GET", "/v1/sessions/{sid}/snapshot", "", ""],
	"tick": ["POST", "/v1/sessions/{sid}/tick", "TickIn", "TickOut"],
	"tie": ["POST", "/v1/sessions/{sid}/ties", "TieIn", "TieOut"],
	"untie": ["DELETE", "/v1/sessions/{sid}/ties/{a}/{b}", "", ""],
	"understand": ["POST", "/v1/sessions/{sid}/understand", "UnderstandIn", "UnderstandOut"],
	"update": ["POST", "/v1/sessions/{sid}/update", "UpdateIn", ""],
	"usage": ["GET", "/v1/usage", "", "UsageOut"],
}


## A new, empty instance of the class with this name, or null.
static func make(name: String):
	match name:
		"ClaimIn":
			return ClaimIn.new()
		"DecideIn":
			return DecideIn.new()
		"EventOut":
			return EventOut.new()
		"GameIn":
			return GameIn.new()
		"GameOut":
			return GameOut.new()
		"HealthOut":
			return HealthOut.new()
		"IntentOut":
			return IntentOut.new()
		"JoinIn":
			return JoinIn.new()
		"LineOut":
			return LineOut.new()
		"ModelIn":
			return ModelIn.new()
		"NarrateIn":
			return NarrateIn.new()
		"NpcIn":
			return NpcIn.new()
		"NpcOut":
			return NpcOut.new()
		"ObserveIn":
			return ObserveIn.new()
		"OfferIn":
			return OfferIn.new()
		"ProjectOut":
			return ProjectOut.new()
		"ProviderIn":
			return ProviderIn.new()
		"ReactIn":
			return ReactIn.new()
		"SessionIn":
			return SessionIn.new()
		"SessionOut":
			return SessionOut.new()
		"TickIn":
			return TickIn.new()
		"TickOut":
			return TickOut.new()
		"TieIn":
			return TieIn.new()
		"TieOut":
			return TieOut.new()
		"UnderstandIn":
			return UnderstandIn.new()
		"UnderstandOut":
			return UnderstandOut.new()
		"UpdateIn":
			return UpdateIn.new()
		"UsageOut":
			return UsageOut.new()
	return null


class ClaimIn extends RefCounted:
	var a: String = ""  ## Who it is about, by id; 'player' is the player
	var at = null  ## integer, or null
	var b: String = ""
	var neg: bool = false  ## A denial: the claim that this did not happen
	var place = null  ## string, or null
	var pred: String = ""  ## What is claimed, from the game's predicates: insulted, paid, was_in

	func read(d: Dictionary):
		if d.has("a"): a = str(d["a"])
		at = int(d["at"]) if d.get("at") != null else null
		if d.has("b"): b = str(d["b"])
		if d.has("neg"): neg = bool(d["neg"])
		place = str(d["place"]) if d.get("place") != null else null
		if d.has("pred"): pred = str(d["pred"])
		return self

	func to_dict() -> Dictionary:
		var d := {}
		d["a"] = a
		if at != null: d["at"] = at
		d["b"] = b
		d["neg"] = neg
		if place != null: d["place"] = place
		d["pred"] = pred
		return d


class DecideIn extends RefCounted:
	var bindings: Dictionary = {}  ## Values the choices name: {culprit}
	var moment: String = ""  ## Which of the NPC's declared choice sets: [[npc.<id>.choices.<moment>]]
	var npc: String = ""
	var situation = null  ## string, or null. What just happened, from the NPC's side, for the model
	var to = null  ## string, or null. Whom an action that states a claim tells it to
	var wait: bool = false  ## Wait for the model's line instead of returning it provisional

	func read(d: Dictionary):
		if d.has("bindings"): bindings = d["bindings"]
		if d.has("moment"): moment = str(d["moment"])
		if d.has("npc"): npc = str(d["npc"])
		situation = str(d["situation"]) if d.get("situation") != null else null
		to = str(d["to"]) if d.get("to") != null else null
		if d.has("wait"): wait = bool(d["wait"])
		return self

	func to_dict() -> Dictionary:
		var d := {}
		d["bindings"] = bindings
		d["moment"] = moment
		d["npc"] = npc
		if situation != null: d["situation"] = situation
		if to != null: d["to"] = to
		d["wait"] = wait
		return d


class EventOut extends RefCounted:
	var actor: String = ""
	var amount = null  ## integer, or null
	var claim: ClaimIn = null
	var id: String = ""
	var loc: String = ""
	var phase: int = 0
	var target = null  ## string, or null
	var truth: bool = false
	var verb: String = ""

	func read(d: Dictionary):
		if d.has("actor"): actor = str(d["actor"])
		amount = int(d["amount"]) if d.get("amount") != null else null
		claim = ClaimIn.new().read(d["claim"]) if d.get("claim") != null else null
		if d.has("id"): id = str(d["id"])
		if d.has("loc"): loc = str(d["loc"])
		if d.has("phase"): phase = int(d["phase"])
		target = str(d["target"]) if d.get("target") != null else null
		if d.has("truth"): truth = bool(d["truth"])
		if d.has("verb"): verb = str(d["verb"])
		return self

	func to_dict() -> Dictionary:
		var d := {}
		d["actor"] = actor
		if amount != null: d["amount"] = amount
		if claim != null: d["claim"] = claim.to_dict()
		d["id"] = id
		d["loc"] = loc
		d["phase"] = phase
		if target != null: d["target"] = target
		d["truth"] = truth
		d["verb"] = verb
		return d


class GameIn extends RefCounted:
	var toml: String = ""  ## The game's definition, as in a game.toml

	func read(d: Dictionary):
		if d.has("toml"): toml = str(d["toml"])
		return self

	func to_dict() -> Dictionary:
		var d := {}
		d["toml"] = toml
		return d


class GameOut extends RefCounted:
	var choices: Dictionary = {}  ## Each NPC's choice sets, by moment
	var digest: String = ""
	var id: String = ""
	var kinds: Array[String] = []  ## Kinds of people the engine may add in play
	var name: String = ""
	var npcs: Array[String] = []
	var places: Array[String] = []

	func read(d: Dictionary):
		if d.has("choices"): choices = d["choices"]
		if d.has("digest"): digest = str(d["digest"])
		if d.has("id"): id = str(d["id"])
		kinds.assign(d.get("kinds", []).map(func(x): return str(x)))
		if d.has("name"): name = str(d["name"])
		npcs.assign(d.get("npcs", []).map(func(x): return str(x)))
		places.assign(d.get("places", []).map(func(x): return str(x)))
		return self

	func to_dict() -> Dictionary:
		var d := {}
		d["choices"] = choices
		d["digest"] = digest
		d["id"] = id
		d["kinds"] = kinds
		d["name"] = name
		d["npcs"] = npcs
		d["places"] = places
		return d


class HealthOut extends RefCounted:
	var offline: bool = false  ## It refuses every connection off this machine (a sidecar, unless --online)
	var ok: bool = false
	var refused: int = 0  ## Connections off this machine it has refused since it started

	func read(d: Dictionary):
		if d.has("offline"): offline = bool(d["offline"])
		if d.has("ok"): ok = bool(d["ok"])
		if d.has("refused"): refused = int(d["refused"])
		return self

	func to_dict() -> Dictionary:
		var d := {}
		d["offline"] = offline
		d["ok"] = ok
		d["refused"] = refused
		return d


class IntentOut extends RefCounted:
	var args: Dictionary = {}  ## Each argument: an id, a whole number, or a claim {pred, a, b, ...}
	var reads: String = ""  ## As put to the player: 'Tell Wren that Garrick insulted her'
	var verb: String = ""

	func read(d: Dictionary):
		if d.has("args"): args = d["args"]
		if d.has("reads"): reads = str(d["reads"])
		if d.has("verb"): verb = str(d["verb"])
		return self

	func to_dict() -> Dictionary:
		var d := {}
		d["args"] = args
		d["reads"] = reads
		d["verb"] = verb
		return d


class JoinIn extends RefCounted:
	var at = null  ## string, or null. Where they are
	var name = null  ## string, or null. What NPCs and the narrator call them
	var player: String = ""  ## A new player's id (not 'player', which every game has, nor an NPC's)

	func read(d: Dictionary):
		at = str(d["at"]) if d.get("at") != null else null
		name = str(d["name"]) if d.get("name") != null else null
		if d.has("player"): player = str(d["player"])
		return self

	func to_dict() -> Dictionary:
		var d := {}
		if at != null: d["at"] = at
		if name != null: d["name"] = name
		d["player"] = player
		return d


class LineOut extends RefCounted:
	var action = null  ## string, or null. What the NPC decided to do, for decide
	var cites: Array[String] = []
	var event = null  ## string, or null. The statement its action logged, if it states a claim
	var id = null  ## string, or null. Poll it at /lines/{id}; null when the NPC had nothing to say
	var npc: String = ""
	var reason: String = ""
	var segments = null  ## array, or null. A told scene, for a game whose narrator is structured: in order, each the narrator's words or one speaker's ({speaker, line, cites})
	var source: String = ""  ## llm, cache or fallback (the game's template line)
	var status: String = ""  ## provisional (more to come), final, or withdrawn (don't show it)
	var text = null  ## string, or null

	func read(d: Dictionary):
		action = str(d["action"]) if d.get("action") != null else null
		cites.assign(d.get("cites", []).map(func(x): return str(x)))
		event = str(d["event"]) if d.get("event") != null else null
		id = str(d["id"]) if d.get("id") != null else null
		if d.has("npc"): npc = str(d["npc"])
		if d.has("reason"): reason = str(d["reason"])
		segments = d["segments"] if d.get("segments") != null else null
		if d.has("source"): source = str(d["source"])
		if d.has("status"): status = str(d["status"])
		text = str(d["text"]) if d.get("text") != null else null
		return self

	func to_dict() -> Dictionary:
		var d := {}
		if action != null: d["action"] = action
		d["cites"] = cites
		if event != null: d["event"] = event
		if id != null: d["id"] = id
		d["npc"] = npc
		d["reason"] = reason
		if segments != null: d["segments"] = segments
		d["source"] = source
		d["status"] = status
		if text != null: d["text"] = text
		return d


class ModelIn extends RefCounted:
	var backup: ProviderIn = null
	var primary: ProviderIn = null

	func read(d: Dictionary):
		backup = ProviderIn.new().read(d["backup"]) if d.get("backup") != null else null
		primary = ProviderIn.new().read(d["primary"]) if d.get("primary") != null else null
		return self

	func to_dict() -> Dictionary:
		var d := {}
		if backup != null: d["backup"] = backup.to_dict()
		if primary != null: d["primary"] = primary.to_dict()
		return d


class NarrateIn extends RefCounted:
	var since: int = 0  ## Tell the story from this phase on
	var to = null  ## string, or null. Tell it to this player: only what they took part in or saw
	var wait: bool = false

	func read(d: Dictionary):
		if d.has("since"): since = int(d["since"])
		to = str(d["to"]) if d.get("to") != null else null
		if d.has("wait"): wait = bool(d["wait"])
		return self

	func to_dict() -> Dictionary:
		var d := {}
		d["since"] = since
		if to != null: d["to"] = to
		d["wait"] = wait
		return d


class NpcIn extends RefCounted:
	var at: String = ""  ## Where they are
	var goal = null  ## string, or null. Their own goal; their kind's if left out
	var id: String = ""  ## A new NPC's id: letters, digits, _ . and -, and not one already taken
	var kind: String = ""  ## A kind of person the game declares: [kind.<id>]
	var name: String = ""  ## What others and the narrator call them
	var persona = null  ## string, or null. Their own persona; their kind's if left out

	func read(d: Dictionary):
		if d.has("at"): at = str(d["at"])
		goal = str(d["goal"]) if d.get("goal") != null else null
		if d.has("id"): id = str(d["id"])
		if d.has("kind"): kind = str(d["kind"])
		if d.has("name"): name = str(d["name"])
		persona = str(d["persona"]) if d.get("persona") != null else null
		return self

	func to_dict() -> Dictionary:
		var d := {}
		d["at"] = at
		if goal != null: d["goal"] = goal
		d["id"] = id
		d["kind"] = kind
		d["name"] = name
		if persona != null: d["persona"] = persona
		return d


class NpcOut extends RefCounted:
	var beliefs: Array = []
	var npc: Dictionary = {}

	func read(d: Dictionary):
		beliefs = d.get("beliefs", [])
		if d.has("npc"): npc = d["npc"]
		return self

	func to_dict() -> Dictionary:
		var d := {}
		d["beliefs"] = beliefs
		d["npc"] = npc
		return d


class ObserveIn extends RefCounted:
	var actor: String = ""
	var amount = null  ## integer, or null
	var at = null  ## string, or null. Where it happened; the actor's place if left out
	var claim: ClaimIn = null  ## What it shows, or, with said, what was said
	var said: bool = false  ## The actor stated the claim: hearers believe it by their trust in them
	var target = null  ## string, or null
	var true_ = null  ## boolean, or null. Whether the claim is true; left out, the ledger decides
	var verb: String = ""  ## What happened: the game's own word for it, as [words.events] names it
	var witnesses: Array[String] = []  ## NPCs who saw it, besides the actor and target

	func read(d: Dictionary):
		if d.has("actor"): actor = str(d["actor"])
		amount = int(d["amount"]) if d.get("amount") != null else null
		at = str(d["at"]) if d.get("at") != null else null
		claim = ClaimIn.new().read(d["claim"]) if d.get("claim") != null else null
		if d.has("said"): said = bool(d["said"])
		target = str(d["target"]) if d.get("target") != null else null
		true_ = bool(d["true"]) if d.get("true") != null else null
		if d.has("verb"): verb = str(d["verb"])
		witnesses.assign(d.get("witnesses", []).map(func(x): return str(x)))
		return self

	func to_dict() -> Dictionary:
		var d := {}
		d["actor"] = actor
		if amount != null: d["amount"] = amount
		if at != null: d["at"] = at
		if claim != null: d["claim"] = claim.to_dict()
		d["said"] = said
		if target != null: d["target"] = target
		if true_ != null: d["true"] = true_
		d["verb"] = verb
		d["witnesses"] = witnesses
		return d


class OfferIn extends RefCounted:
	var args: Dictionary = {}  ## Each argument's choices now, narrowing the game's: ids for an npc, player, place or choice; {min, max} for an amount; {preds, subjects} for a claim. Left out, the game's (an npc: whoever is where the player is)
	var verb: String = ""  ## An intent the game declares: [intents.<verb>]

	func read(d: Dictionary):
		if d.has("args"): args = d["args"]
		if d.has("verb"): verb = str(d["verb"])
		return self

	func to_dict() -> Dictionary:
		var d := {}
		d["args"] = args
		d["verb"] = verb
		return d


class ProjectOut extends RefCounted:
	var caps: Dictionary = {}  ## 0 means no cap
	var id: String = ""
	var model = null  ## object, or null. Its own model settings, keys left out; null: the host's
	var name: String = ""
	var sessions: int = 0  ## Sessions open now
	var today: Dictionary = {}  ## Model calls and tokens so far today (UTC)

	func read(d: Dictionary):
		if d.has("caps"): caps = d["caps"]
		if d.has("id"): id = str(d["id"])
		model = d["model"] if d.get("model") != null else null
		if d.has("name"): name = str(d["name"])
		if d.has("sessions"): sessions = int(d["sessions"])
		if d.has("today"): today = d["today"]
		return self

	func to_dict() -> Dictionary:
		var d := {}
		d["caps"] = caps
		d["id"] = id
		if model != null: d["model"] = model
		d["name"] = name
		d["sessions"] = sessions
		d["today"] = today
		return d


class ProviderIn extends RefCounted:
	var api_key: String = ""  ## Kept sealed; never sent back
	var api_version: String = ""
	var base_url: String = ""  ## The endpoint; the profile's if left out
	var extra = null  ## object, or null
	var model: String = ""
	var profile: String = ""  ## A provider profile: openai, azure, anthropic, gemini, groq, ...
	var structured: bool = true
	var timeout = null  ## number, or null

	func read(d: Dictionary):
		if d.has("api_key"): api_key = str(d["api_key"])
		if d.has("api_version"): api_version = str(d["api_version"])
		if d.has("base_url"): base_url = str(d["base_url"])
		extra = d["extra"] if d.get("extra") != null else null
		if d.has("model"): model = str(d["model"])
		if d.has("profile"): profile = str(d["profile"])
		if d.has("structured"): structured = bool(d["structured"])
		timeout = float(d["timeout"]) if d.get("timeout") != null else null
		return self

	func to_dict() -> Dictionary:
		var d := {}
		d["api_key"] = api_key
		d["api_version"] = api_version
		d["base_url"] = base_url
		if extra != null: d["extra"] = extra
		d["model"] = model
		d["profile"] = profile
		d["structured"] = structured
		if timeout != null: d["timeout"] = timeout
		return d


class ReactIn extends RefCounted:
	var cites: Array[String] = []  ## Event or belief ids the line rests on
	var fill: Dictionary = {}  ## Values for the template's {placeholders}
	var npc: String = ""
	var situation = null  ## string, or null
	var trigger: String = ""  ## The line's key in [npc.<id>.lines]
	var wait: bool = false

	func read(d: Dictionary):
		cites.assign(d.get("cites", []).map(func(x): return str(x)))
		if d.has("fill"): fill = d["fill"]
		if d.has("npc"): npc = str(d["npc"])
		situation = str(d["situation"]) if d.get("situation") != null else null
		if d.has("trigger"): trigger = str(d["trigger"])
		if d.has("wait"): wait = bool(d["wait"])
		return self

	func to_dict() -> Dictionary:
		var d := {}
		d["cites"] = cites
		d["fill"] = fill
		d["npc"] = npc
		if situation != null: d["situation"] = situation
		d["trigger"] = trigger
		d["wait"] = wait
		return d


class SessionIn extends RefCounted:
	var game: String = ""  ## A game the server loaded, by its id
	var seed: int = 0
	var snapshot = null  ## object, or null. Restore this snapshot instead of starting fresh

	func read(d: Dictionary):
		if d.has("game"): game = str(d["game"])
		if d.has("seed"): seed = int(d["seed"])
		snapshot = d["snapshot"] if d.get("snapshot") != null else null
		return self

	func to_dict() -> Dictionary:
		var d := {}
		d["game"] = game
		d["seed"] = seed
		if snapshot != null: d["snapshot"] = snapshot
		return d


class SessionOut extends RefCounted:
	var game: String = ""
	var phase: int = 0
	var session: String = ""

	func read(d: Dictionary):
		if d.has("game"): game = str(d["game"])
		if d.has("phase"): phase = int(d["phase"])
		if d.has("session"): session = str(d["session"])
		return self

	func to_dict() -> Dictionary:
		var d := {}
		d["game"] = game
		d["phase"] = phase
		d["session"] = session
		return d


class TickIn extends RefCounted:
	var steps: int = 1

	func read(d: Dictionary):
		if d.has("steps"): steps = int(d["steps"])
		return self

	func to_dict() -> Dictionary:
		var d := {}
		d["steps"] = steps
		return d


class TickOut extends RefCounted:
	var events: Array[EventOut] = []
	var moves: Array = []
	var phase: int = 0

	func read(d: Dictionary):
		events.assign(d.get("events", []).map(func(x): return EventOut.new().read(x)))
		moves = d.get("moves", [])
		if d.has("phase"): phase = int(d["phase"])
		return self

	func to_dict() -> Dictionary:
		var d := {}
		d["events"] = events.map(func(x): return x.to_dict())
		d["moves"] = moves
		d["phase"] = phase
		return d


class TieIn extends RefCounted:
	var a: String = ""
	var b: String = ""
	var kind: String = ""  ## A kind of tie the game's [gossip] along declares

	func read(d: Dictionary):
		if d.has("a"): a = str(d["a"])
		if d.has("b"): b = str(d["b"])
		if d.has("kind"): kind = str(d["kind"])
		return self

	func to_dict() -> Dictionary:
		var d := {}
		d["a"] = a
		d["b"] = b
		d["kind"] = kind
		return d


class TieOut extends RefCounted:
	var between: Array[String] = []
	var kind: String = ""

	func read(d: Dictionary):
		between.assign(d.get("between", []).map(func(x): return str(x)))
		if d.has("kind"): kind = str(d["kind"])
		return self

	func to_dict() -> Dictionary:
		var d := {}
		d["between"] = between
		d["kind"] = kind
		return d


class UnderstandIn extends RefCounted:
	var offered = null  ## array, or null. The intents open now, as the engine's buttons have them; left out, every intent the game declares
	var player: String = "player"  ## Who typed it
	var text: String = ""  ## What the player typed
	var to = null  ## string, or null. The NPC the player is speaking to

	func read(d: Dictionary):
		offered = d["offered"] if d.get("offered") != null else null
		if d.has("player"): player = str(d["player"])
		if d.has("text"): text = str(d["text"])
		to = str(d["to"]) if d.get("to") != null else null
		return self

	func to_dict() -> Dictionary:
		var d := {}
		if offered != null: d["offered"] = offered
		d["player"] = player
		d["text"] = text
		if to != null: d["to"] = to
		return d


class UnderstandOut extends RefCounted:
	var intent: IntentOut = null  ## The act, or for talk, the game's talk intent if it declares one
	var path: String = ""  ## What answered: guard, bank, near, model, cache or none
	var readings: Array[IntentOut] = []  ## For ask: what the words might do, most likely first
	var status: String = ""  ## act (apply the intent), ask (put the readings to the player first) or talk (words that do nothing else)
	var sure: String = ""  ## certain, likely or unsure
	var why: String = ""

	func read(d: Dictionary):
		intent = IntentOut.new().read(d["intent"]) if d.get("intent") != null else null
		if d.has("path"): path = str(d["path"])
		readings.assign(d.get("readings", []).map(func(x): return IntentOut.new().read(x)))
		if d.has("status"): status = str(d["status"])
		if d.has("sure"): sure = str(d["sure"])
		if d.has("why"): why = str(d["why"])
		return self

	func to_dict() -> Dictionary:
		var d := {}
		if intent != null: d["intent"] = intent.to_dict()
		d["path"] = path
		d["readings"] = readings.map(func(x): return x.to_dict())
		d["status"] = status
		d["sure"] = sure
		d["why"] = why
		return d


class UpdateIn extends RefCounted:
	var drives = null  ## object, or null. Drives to set, 0 to 10
	var flags = null  ## object, or null. Flags to set; null removes one
	var loc = null  ## string, or null
	var npc: String = ""  ## An NPC id, or 'player' (which takes only loc)
	var nudge = null  ## object, or null. Drives to move by a step, kept within 0 to 10
	var trust_in = null  ## object, or null. Trust to set, -5 to 5

	func read(d: Dictionary):
		drives = d["drives"] if d.get("drives") != null else null
		flags = d["flags"] if d.get("flags") != null else null
		loc = str(d["loc"]) if d.get("loc") != null else null
		if d.has("npc"): npc = str(d["npc"])
		nudge = d["nudge"] if d.get("nudge") != null else null
		trust_in = d["trust_in"] if d.get("trust_in") != null else null
		return self

	func to_dict() -> Dictionary:
		var d := {}
		if drives != null: d["drives"] = drives
		if flags != null: d["flags"] = flags
		if loc != null: d["loc"] = loc
		d["npc"] = npc
		if nudge != null: d["nudge"] = nudge
		if trust_in != null: d["trust_in"] = trust_in
		return d


class UsageOut extends RefCounted:
	var at: float = 0.0
	var call_type: String = ""
	var completion_tokens = null  ## integer, or null
	var kind: String = ""  ## call (a model call), line (a line settled) or capped (a call the caps refused)
	var latency_ms = null  ## integer, or null
	var ok: bool = false
	var project: String = ""
	var prompt_tokens = null  ## integer, or null
	var provider = null  ## string, or null
	var session = null  ## string, or null
	var source = null  ## string, or null. For a line: llm, cache or fallback. For capped: which cap

	func read(d: Dictionary):
		if d.has("at"): at = float(d["at"])
		if d.has("call_type"): call_type = str(d["call_type"])
		completion_tokens = int(d["completion_tokens"]) if d.get("completion_tokens") != null else null
		if d.has("kind"): kind = str(d["kind"])
		latency_ms = int(d["latency_ms"]) if d.get("latency_ms") != null else null
		if d.has("ok"): ok = bool(d["ok"])
		if d.has("project"): project = str(d["project"])
		prompt_tokens = int(d["prompt_tokens"]) if d.get("prompt_tokens") != null else null
		provider = str(d["provider"]) if d.get("provider") != null else null
		session = str(d["session"]) if d.get("session") != null else null
		source = str(d["source"]) if d.get("source") != null else null
		return self

	func to_dict() -> Dictionary:
		var d := {}
		d["at"] = at
		d["call_type"] = call_type
		if completion_tokens != null: d["completion_tokens"] = completion_tokens
		d["kind"] = kind
		if latency_ms != null: d["latency_ms"] = latency_ms
		d["ok"] = ok
		d["project"] = project
		if prompt_tokens != null: d["prompt_tokens"] = prompt_tokens
		if provider != null: d["provider"] = provider
		if session != null: d["session"] = session
		if source != null: d["source"] = source
		return d
