// Generated by tools/sdk_gen.py from docs/openapi-v1.json: don't edit it; change the server, then regenerate.
//
// The /v1 contract in C#: a class per schema, with typed properties named as C# names them and serialised as
// the server names them, and the route table the client calls through. Nothing here touches UnityEngine, so
// it builds under plain .NET as well (netstandard2.1, C# 9).
#nullable enable
using System.Collections.Generic;
using Newtonsoft.Json;
using Newtonsoft.Json.Linq;

namespace Thespis.Api
{
    /// <summary>A /v1 route: its method and path (with {params}), and its request and reply schemas.</summary>
    public sealed class Route
    {
        public string Method { get; }
        public string Path { get; }
        public string Request { get; }
        public string Reply { get; }

        public Route(string method, string path, string request, string reply)
        {
            Method = method;
            Path = path;
            Request = request;
            Reply = reply;
        }
    }

    public static class Routes
    {
        public const string Version = "v1";
        public static readonly Route ListGames = new Route("GET", "/v1/games", "", "GameOut");
        public static readonly Route DeleteGame = new Route("DELETE", "/v1/games/{gid}", "", "");
        public static readonly Route PutGame = new Route("PUT", "/v1/games/{gid}", "GameIn", "GameOut");
        public static readonly Route Health = new Route("GET", "/v1/health", "", "HealthOut");
        public static readonly Route GetProject = new Route("GET", "/v1/project", "", "ProjectOut");
        public static readonly Route DeleteModel = new Route("DELETE", "/v1/project/model", "", "");
        public static readonly Route PutModel = new Route("PUT", "/v1/project/model", "ModelIn", "");
        public static readonly Route OpenSession = new Route("POST", "/v1/sessions", "SessionIn", "SessionOut");
        public static readonly Route CloseSession = new Route("DELETE", "/v1/sessions/{sid}", "", "");
        public static readonly Route Decide = new Route("POST", "/v1/sessions/{sid}/decide", "DecideIn", "LineOut");
        public static readonly Route Line = new Route("GET", "/v1/sessions/{sid}/lines/{lid}", "", "LineOut");
        public static readonly Route Narrate = new Route("POST", "/v1/sessions/{sid}/narrate", "NarrateIn", "LineOut");
        public static readonly Route Inspect = new Route("GET", "/v1/sessions/{sid}/npcs/{npc}", "", "NpcOut");
        public static readonly Route Observe = new Route("POST", "/v1/sessions/{sid}/observe", "ObserveIn", "EventOut");
        public static readonly Route Join = new Route("POST", "/v1/sessions/{sid}/players", "JoinIn", "");
        public static readonly Route React = new Route("POST", "/v1/sessions/{sid}/react", "ReactIn", "LineOut");
        public static readonly Route Snapshot = new Route("GET", "/v1/sessions/{sid}/snapshot", "", "");
        public static readonly Route Tick = new Route("POST", "/v1/sessions/{sid}/tick", "TickIn", "TickOut");
        public static readonly Route Update = new Route("POST", "/v1/sessions/{sid}/update", "UpdateIn", "");
        public static readonly Route Usage = new Route("GET", "/v1/usage", "", "UsageOut");
    }

    public class ClaimIn
    {
        /// <summary>Who it is about, by id; 'player' is the player</summary>
        [JsonProperty("a")]
        public string A { get; set; } = "";

        [JsonProperty("at", NullValueHandling = NullValueHandling.Ignore)]
        public int? At { get; set; }

        [JsonProperty("b")]
        public string B { get; set; } = "";

        /// <summary>A denial: the claim that this did not happen</summary>
        [JsonProperty("neg")]
        public bool Neg { get; set; } = false;

        [JsonProperty("place", NullValueHandling = NullValueHandling.Ignore)]
        public string? Place { get; set; }

        /// <summary>What is claimed, from the game's predicates: insulted, paid, was_in</summary>
        [JsonProperty("pred")]
        public string Pred { get; set; } = "";
    }

    public class DecideIn
    {
        /// <summary>Values the choices name: {culprit}</summary>
        [JsonProperty("bindings")]
        public Dictionary<string, object> Bindings { get; set; } = new();

        /// <summary>Which of the NPC's declared choice sets: [[npc.<id>.choices.<moment>]]</summary>
        [JsonProperty("moment")]
        public string Moment { get; set; } = "";

        [JsonProperty("npc")]
        public string Npc { get; set; } = "";

        /// <summary>What just happened, from the NPC's side, for the model</summary>
        [JsonProperty("situation", NullValueHandling = NullValueHandling.Ignore)]
        public string? Situation { get; set; }

        /// <summary>Whom an action that states a claim tells it to</summary>
        [JsonProperty("to", NullValueHandling = NullValueHandling.Ignore)]
        public string? To { get; set; }

        /// <summary>Wait for the model's line instead of returning it provisional</summary>
        [JsonProperty("wait")]
        public bool Wait { get; set; } = false;
    }

    public class EventOut
    {
        [JsonProperty("actor")]
        public string Actor { get; set; } = "";

        [JsonProperty("amount", NullValueHandling = NullValueHandling.Ignore)]
        public int? Amount { get; set; }

        [JsonProperty("claim", NullValueHandling = NullValueHandling.Ignore)]
        public ClaimIn? Claim { get; set; }

        [JsonProperty("id")]
        public string Id { get; set; } = "";

        [JsonProperty("loc")]
        public string Loc { get; set; } = "";

        [JsonProperty("phase")]
        public int Phase { get; set; }

        [JsonProperty("target", NullValueHandling = NullValueHandling.Ignore)]
        public string? Target { get; set; }

        [JsonProperty("truth")]
        public bool Truth { get; set; }

        [JsonProperty("verb")]
        public string Verb { get; set; } = "";
    }

    public class GameIn
    {
        /// <summary>The game's definition, as in a game.toml</summary>
        [JsonProperty("toml")]
        public string Toml { get; set; } = "";
    }

    public class GameOut
    {
        /// <summary>Each NPC's choice sets, by moment</summary>
        [JsonProperty("choices")]
        public Dictionary<string, List<string>> Choices { get; set; } = new();

        [JsonProperty("digest")]
        public string Digest { get; set; } = "";

        [JsonProperty("id")]
        public string Id { get; set; } = "";

        [JsonProperty("name")]
        public string Name { get; set; } = "";

        [JsonProperty("npcs")]
        public List<string> Npcs { get; set; } = new();

        [JsonProperty("places")]
        public List<string> Places { get; set; } = new();
    }

    public class HealthOut
    {
        /// <summary>It refuses every connection off this machine (a sidecar, unless --online)</summary>
        [JsonProperty("offline")]
        public bool Offline { get; set; }

        [JsonProperty("ok")]
        public bool Ok { get; set; }

        /// <summary>Connections off this machine it has refused since it started</summary>
        [JsonProperty("refused")]
        public int Refused { get; set; }
    }

    public class JoinIn
    {
        /// <summary>Where they are</summary>
        [JsonProperty("at", NullValueHandling = NullValueHandling.Ignore)]
        public string? At { get; set; }

        /// <summary>What NPCs and the narrator call them</summary>
        [JsonProperty("name", NullValueHandling = NullValueHandling.Ignore)]
        public string? Name { get; set; }

        /// <summary>A new player's id (not 'player', which every game has, nor an NPC's)</summary>
        [JsonProperty("player")]
        public string Player { get; set; } = "";
    }

    public class LineOut
    {
        /// <summary>What the NPC decided to do, for decide</summary>
        [JsonProperty("action", NullValueHandling = NullValueHandling.Ignore)]
        public string? Action { get; set; }

        [JsonProperty("cites")]
        public List<string> Cites { get; set; } = new();

        /// <summary>The statement its action logged, if it states a claim</summary>
        [JsonProperty("event", NullValueHandling = NullValueHandling.Ignore)]
        public string? Event { get; set; }

        /// <summary>Poll it at /lines/{id}; null when the NPC had nothing to say</summary>
        [JsonProperty("id", NullValueHandling = NullValueHandling.Ignore)]
        public string? Id { get; set; }

        [JsonProperty("npc")]
        public string Npc { get; set; } = "";

        [JsonProperty("reason")]
        public string Reason { get; set; } = "";

        /// <summary>A told scene, for a game whose narrator is structured: in order, each the narrator's words or one speaker's ({speaker, line, cites})</summary>
        [JsonProperty("segments", NullValueHandling = NullValueHandling.Ignore)]
        public List<JObject>? Segments { get; set; }

        /// <summary>llm, cache or fallback (the game's template line)</summary>
        [JsonProperty("source")]
        public string Source { get; set; } = "";

        /// <summary>provisional (more to come), final, or withdrawn (don't show it)</summary>
        [JsonProperty("status")]
        public string Status { get; set; } = "";

        [JsonProperty("text", NullValueHandling = NullValueHandling.Ignore)]
        public string? Text { get; set; }
    }

    public class ModelIn
    {
        [JsonProperty("backup", NullValueHandling = NullValueHandling.Ignore)]
        public ProviderIn? Backup { get; set; }

        [JsonProperty("primary")]
        public ProviderIn Primary { get; set; } = new();
    }

    public class NarrateIn
    {
        /// <summary>Tell the story from this phase on</summary>
        [JsonProperty("since")]
        public int Since { get; set; } = 0;

        /// <summary>Tell it to this player: only what they took part in or saw</summary>
        [JsonProperty("to", NullValueHandling = NullValueHandling.Ignore)]
        public string? To { get; set; }

        [JsonProperty("wait")]
        public bool Wait { get; set; } = false;
    }

    public class NpcOut
    {
        [JsonProperty("beliefs")]
        public List<JObject> Beliefs { get; set; } = new();

        [JsonProperty("npc")]
        public JObject Npc { get; set; } = new();
    }

    public class ObserveIn
    {
        [JsonProperty("actor")]
        public string Actor { get; set; } = "";

        [JsonProperty("amount", NullValueHandling = NullValueHandling.Ignore)]
        public int? Amount { get; set; }

        /// <summary>Where it happened; the actor's place if left out</summary>
        [JsonProperty("at", NullValueHandling = NullValueHandling.Ignore)]
        public string? At { get; set; }

        /// <summary>What it shows, or, with said, what was said</summary>
        [JsonProperty("claim", NullValueHandling = NullValueHandling.Ignore)]
        public ClaimIn? Claim { get; set; }

        /// <summary>The actor stated the claim: hearers believe it by their trust in them</summary>
        [JsonProperty("said")]
        public bool Said { get; set; } = false;

        [JsonProperty("target", NullValueHandling = NullValueHandling.Ignore)]
        public string? Target { get; set; }

        /// <summary>Whether the claim is true; left out, the ledger decides</summary>
        [JsonProperty("true", NullValueHandling = NullValueHandling.Ignore)]
        public bool? True { get; set; }

        /// <summary>What happened: the game's own word for it, as [words.events] names it</summary>
        [JsonProperty("verb")]
        public string Verb { get; set; } = "";

        /// <summary>NPCs who saw it, besides the actor and target</summary>
        [JsonProperty("witnesses")]
        public List<string> Witnesses { get; set; } = new();
    }

    public class ProjectOut
    {
        /// <summary>0 means no cap</summary>
        [JsonProperty("caps")]
        public Dictionary<string, int> Caps { get; set; } = new();

        [JsonProperty("id")]
        public string Id { get; set; } = "";

        /// <summary>Its own model settings, keys left out; null: the host's</summary>
        [JsonProperty("model", NullValueHandling = NullValueHandling.Ignore)]
        public JObject? Model { get; set; }

        [JsonProperty("name")]
        public string Name { get; set; } = "";

        /// <summary>Sessions open now</summary>
        [JsonProperty("sessions")]
        public int Sessions { get; set; }

        /// <summary>Model calls and tokens so far today (UTC)</summary>
        [JsonProperty("today")]
        public Dictionary<string, int> Today { get; set; } = new();
    }

    public class ProviderIn
    {
        /// <summary>Kept sealed; never sent back</summary>
        [JsonProperty("api_key")]
        public string ApiKey { get; set; } = "";

        [JsonProperty("api_version")]
        public string ApiVersion { get; set; } = "";

        /// <summary>The endpoint; the profile's if left out</summary>
        [JsonProperty("base_url")]
        public string BaseUrl { get; set; } = "";

        [JsonProperty("extra", NullValueHandling = NullValueHandling.Ignore)]
        public JObject? Extra { get; set; }

        [JsonProperty("model")]
        public string Model { get; set; } = "";

        /// <summary>A provider profile: openai, azure, anthropic, gemini, groq, ...</summary>
        [JsonProperty("profile")]
        public string Profile { get; set; } = "";

        [JsonProperty("structured")]
        public bool Structured { get; set; } = true;

        [JsonProperty("timeout", NullValueHandling = NullValueHandling.Ignore)]
        public double? Timeout { get; set; }
    }

    public class ReactIn
    {
        /// <summary>Event or belief ids the line rests on</summary>
        [JsonProperty("cites")]
        public List<string> Cites { get; set; } = new();

        /// <summary>Values for the template's {placeholders}</summary>
        [JsonProperty("fill")]
        public Dictionary<string, object> Fill { get; set; } = new();

        [JsonProperty("npc")]
        public string Npc { get; set; } = "";

        [JsonProperty("situation", NullValueHandling = NullValueHandling.Ignore)]
        public string? Situation { get; set; }

        /// <summary>The line's key in [npc.<id>.lines]</summary>
        [JsonProperty("trigger")]
        public string Trigger { get; set; } = "";

        [JsonProperty("wait")]
        public bool Wait { get; set; } = false;
    }

    public class SessionIn
    {
        /// <summary>A game the server loaded, by its id</summary>
        [JsonProperty("game")]
        public string Game { get; set; } = "";

        [JsonProperty("seed")]
        public int Seed { get; set; } = 0;

        /// <summary>Restore this snapshot instead of starting fresh</summary>
        [JsonProperty("snapshot", NullValueHandling = NullValueHandling.Ignore)]
        public JObject? Snapshot { get; set; }
    }

    public class SessionOut
    {
        [JsonProperty("game")]
        public string Game { get; set; } = "";

        [JsonProperty("phase")]
        public int Phase { get; set; }

        [JsonProperty("session")]
        public string Session { get; set; } = "";
    }

    public class TickIn
    {
        [JsonProperty("steps")]
        public int Steps { get; set; } = 1;
    }

    public class TickOut
    {
        [JsonProperty("events")]
        public List<EventOut> Events { get; set; } = new();

        [JsonProperty("moves")]
        public List<Dictionary<string, string>> Moves { get; set; } = new();

        [JsonProperty("phase")]
        public int Phase { get; set; }
    }

    public class UpdateIn
    {
        /// <summary>Drives to set, 0 to 10</summary>
        [JsonProperty("drives", NullValueHandling = NullValueHandling.Ignore)]
        public Dictionary<string, int>? Drives { get; set; }

        /// <summary>Flags to set; null removes one</summary>
        [JsonProperty("flags", NullValueHandling = NullValueHandling.Ignore)]
        public JObject? Flags { get; set; }

        [JsonProperty("loc", NullValueHandling = NullValueHandling.Ignore)]
        public string? Loc { get; set; }

        /// <summary>An NPC id, or 'player' (which takes only loc)</summary>
        [JsonProperty("npc")]
        public string Npc { get; set; } = "";

        /// <summary>Drives to move by a step, kept within 0 to 10</summary>
        [JsonProperty("nudge", NullValueHandling = NullValueHandling.Ignore)]
        public Dictionary<string, int>? Nudge { get; set; }

        /// <summary>Trust to set, -5 to 5</summary>
        [JsonProperty("trust_in", NullValueHandling = NullValueHandling.Ignore)]
        public Dictionary<string, int>? TrustIn { get; set; }
    }

    public class UsageOut
    {
        [JsonProperty("at")]
        public double At { get; set; }

        [JsonProperty("call_type")]
        public string CallType { get; set; } = "";

        [JsonProperty("completion_tokens", NullValueHandling = NullValueHandling.Ignore)]
        public int? CompletionTokens { get; set; }

        /// <summary>call (a model call), line (a line settled) or capped (a call the caps refused)</summary>
        [JsonProperty("kind")]
        public string Kind { get; set; } = "";

        [JsonProperty("latency_ms", NullValueHandling = NullValueHandling.Ignore)]
        public int? LatencyMs { get; set; }

        [JsonProperty("ok")]
        public bool Ok { get; set; }

        [JsonProperty("project")]
        public string Project { get; set; } = "";

        [JsonProperty("prompt_tokens", NullValueHandling = NullValueHandling.Ignore)]
        public int? PromptTokens { get; set; }

        [JsonProperty("provider", NullValueHandling = NullValueHandling.Ignore)]
        public string? Provider { get; set; }

        [JsonProperty("session", NullValueHandling = NullValueHandling.Ignore)]
        public string? Session { get; set; }

        /// <summary>For a line: llm, cache or fallback. For capped: which cap</summary>
        [JsonProperty("source", NullValueHandling = NullValueHandling.Ignore)]
        public string? Source { get; set; }
    }
}
